version: '3'
service:
    web:
        image: id/imagename:lable
        restart: on-failure
        container_name: my-web-container_name
        ports:
            - 8080:8080
        networks:
            - example-net
        depends_on:
            - db
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure

    db:
        images: mysql:5.6
        restart: on-failure
        container_name: mysql-container
        ports:
            - 3306:3306
        volumes:
            - example-mysql: /var/lib/mysql
        networks:
            - example-net:
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mysql_database
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints: [node.role == manager]

networks:
    example-net:

volumes:
    example-mysql:
